<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInita3a9975f78650ff5ea5ee0af3a4770d3
{
    public static $prefixLengthsPsr4 = array (
        'E' => 
        array (
            'Elliptic\\' => 9,
        ),
        'B' => 
        array (
            'BN\\' => 3,
            'BI\\' => 3,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Elliptic\\' => 
        array (
            0 => __DIR__ . '/..' . '/simplito/elliptic-php/lib',
        ),
        'BN\\' => 
        array (
            0 => __DIR__ . '/..' . '/simplito/bn-php/lib',
        ),
        'BI\\' => 
        array (
            0 => __DIR__ . '/..' . '/simplito/bigint-wrapper-php/lib',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInita3a9975f78650ff5ea5ee0af3a4770d3::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInita3a9975f78650ff5ea5ee0af3a4770d3::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInita3a9975f78650ff5ea5ee0af3a4770d3::$classMap;

        }, null, ClassLoader::class);
    }
}
